# Generated by Django 2.2 on 2022-12-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221218_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cedula',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
