# Generated by Django 2.2 on 2022-12-18 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20221203_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentotest',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 15, 44, 35, 295433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tests',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 15, 44, 35, 295433, tzinfo=utc)),
        ),
    ]
