# Generated by Django 2.2 on 2022-12-18 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20221218_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentotest',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 22, 27, 17, 858009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='score_question',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 22, 27, 17, 858009, tzinfo=utc)),
        ),
    ]
