# Generated by Django 2.2 on 2022-12-19 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20221218_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentotest',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 2, 54, 47, 99647)),
        ),
        migrations.AlterField(
            model_name='tests',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 2, 54, 47, 94643)),
        ),
    ]
